# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

# put together a table for viewing in a report.  just makes it reasonable in size putting random
# columns beside eachother.
my_untidy_table <- function(d){
  d_prep <- d %>%
    tibble::rownames_to_column() %>%
    mutate(rowname = as.numeric(rowname),
           col_id = case_when(rowname <= ceiling(nrow(.)/2) ~ 1,
                              T ~ 2)) %>%
    select(-rowname)
  d1 <- d_prep %>%
    filter(col_id == 1) %>%
    select(-col_id)
  d1$row_match <- seq(1:nrow(d1))
  d2 <- d_prep %>%
    filter(col_id == 2) %>%
    select(-col_id) %>%
    purrr::set_names(nm = '-')
  d2$row_match <- seq(1:nrow(d2))
  ##join them together
  d_joined <- left_join(d1, d2, by = 'row_match') %>%
    select(-row_match)
}

my_untidy_table_2 <- function(d, n_cols = 2) {
  chk::chk_data(d)
  chk::chk_equal(ncol(d), 1)

  # Extract column content and name
  col_data <- d[[1]]
  col_name <- names(d)[1]

  # Pad the vector with NA to fill the final row
  n_items <- length(col_data)
  n_rows <- ceiling(n_items / n_cols)
  padded <- c(col_data, rep(NA, n_cols * n_rows - n_items))

  # Reshape into matrix and convert to dataframe
  mat <- matrix(padded, ncol = n_cols, byrow = TRUE)
  df_out <- as.data.frame(mat)

  # Set colnames: first is original name, rest are "-"
  colnames(df_out) <- c(col_name, rep("-", n_cols - 1))

  return(df_out)
}
